site:
    title: ljgo 静态博客
    introduce: 简单容易
    limit: 10
    theme: "themes/default"
    url:
    comments:
        giscus:
            enable: true
            repo: example
            repo_id: xxx
            category: xxx
            category_id: xxx
            mapping: xxx
            reactions_eanbled: true
            theme: light
    github:
    facebook:
    twitter:
serve:
    addr: "localhost:3000"

publish:
    cmd: |
        git add -A
        git commit -m "update"
        git push origin

